name: Build, Test and Publish

on:
  push:
    branches: [ "main" ] # 只有推送到 main 分支时才触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # 必须开启写入权限才能推送镜像

    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # --- 【自动化测试环节】 ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      #   cache: 'npm' # 自动缓存 node_modules，下次跑快 2 倍。本项目没有package.json 故先屏蔽

      # - name: Install dependencies
      #   run: npm install

      - name: Run Crawler Test
        # 自动测试用例，只要这一行报错（Exit Code != 0），后面的打包步骤就不会执行
        run: echo "Skip testing for now..." && true # run: node tests/test-spider.js

      # --- 【登录与打包环节】 ---
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # GitHub 自动生成的 Token，无需手动设置

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # 镜像地址规则：ghcr.io/用户名/仓库名:latest
          tags: ghcr.io/${{ github.repository }}:latest
